services:
  postgres:
    container_name: postgres_container_finance
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - postgres_finance:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_finance:
